### PR TITLE
Make create_table reversible

### PR DESCRIPTION
**Pull request by mxl519**
Summary
---
Make create_table migrations reversible

### Necessary Changes
1. Fix mixin to not try to invert adding/dropping of saseo trigger

### Low-Priority Changes

Review
---

- [ ] Does the code solve the problem?
- [ ] Does the code have sufficient test coverage for both positive and negative test cases?
- [ ] Is the code understandable and followable?
- [ ] Does the code have the right amount of complexity?
- [ ] Is it a long-term solution or, if a short-term solution, is there a followup task?
- [ ] Database changes detected. Please review the db/migrate folder.

### CODE REVIEW

**Comment by mxl519** [comment]
@nkeyes Hey dude, could you please take a look at this? There's a bit more discussion here (https://github.com/avantcredit/avant-basic/pull/13627#discussion_r61201076), but basically our `create_table` migrations can't be automatically rolled back right now, and require manual `up` and `down` definitions. Since the mixin's functionality is naturally self-cleaning anyways, we only need it for `up` actions.

Thanks!

**Comment by bhgames** [comment]
@nkeyes in Japan eating candy and stuff

**Comment by mxl519** [comment]
Wish I had candy... ( ᵒ̴̶̷̥́ _ᵒ̴̶̷̣̥̀ )

Yeah, no rush at all on this.

**Comment by nkeyes** [comment]
Tests?

**Comment by bhgames** [comment]
What're those?

**Comment by mxl519** [comment]
@nkeyes Added.

**Comment by nkeyes** [comment]
👍

**Pull request merged**
